language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.0
  - 1.1
  - 1.2
  - 1.3
notifications:
  email: false
codecov: true
coveralls: true
branches:
  only:
  - master
matrix:
  allow_failures:
  - julia: nightly
